--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: openmrs-deploy
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: openmrs-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: openmrs-pod
      labels:
        app: openmrs-app
        ver: "1.0"
    spec:
      containers:
        - name: openmrs-pods
          image: sai3369/openmrs:latest
          command: 
            - catalina.sh
            - run
            - 0.0.0.0:8080
          env: 
            - name:  OMRS_DB_HOSTNAME
              value: gowtham
            - name: OMRS_DB_NAME
              value: openmrs
            - name:  OMRS_DB_USERNAME
              value: gowtham
            - name:  OMRS_DB_PASSWORD
              value: gowtham123
            - name: OMRS_ADMIN_USER_PASSWORD
              value: gowtham
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /openmrs/data/
              name: openmrs-app-storage
      volumes:
        - name: openmrs-app-storage
          persistentVolumeClaim:
            claimName: openmrs-pvc
