
# jenkins & Nginix in one pod -2 

---
apiVersion: v1
kind: Pod
metadata:
  name: two-pods
spec: 
  containers:
    - image: jenkins/jenkins
      name: jenkins-con
      ports:
        - containerPort: 8080
          protocol: TCP 
    - image: nginx:latest 
      name: nginx-con
      ports: 
        - containerPort: 80 
          protocol: TCP 
# end of activity 2


