--- 
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
spec:
  selector:
      app: spc
  type: NodePort
  ports:
    - name: web_port
      protocol: TCP
      port: 4000
      targetPort: 8080



