--- 
kind: Deployment 
apiVersion: apps/v1
metadata:
  name: scr-deployment
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels: 
      app: scr
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadta:
      name: scr-pods
      labels:
        app: scr 
        version: '1.0'
    spec:
      activeDeadlineSeconds: 5
      containers:
        - image: gowthi1404/scr:1.0
          name: scr
          ports:
            - containerPort: 8080
              protocol: TCP 
              name: webport
          env:
            - name: MYSQL_HOST
              value: sql-service
            - name: MYSQL_DATABASE
              value: courses
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_USER
              value: gowtham
            - name: MYSQL_PASSWORD
              value: gowtham@123
         
      
      
--- 
kind: Service 
apiVersion: v1 
metadata:
  name: scr-service
spec:
  selector: 
    app: scr
  type: LoadBalancer
  ports:
    - name: scr-port
      type: TCP 
      port: 8080
      targetPort: 8080
