--- 
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: spc-pods
spec:
  minReadySeconds: 5
  replicas: 3
  selector: 
    matchLabels:
      app: spc
  template:
    metadata:
      name: spc-pods 
      labels: 
        app: spc
        env: qa
    spec:
      containers:
        - name: spc-pods
          image: gowthi1404/spc:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
