# deployemnt for saleor core
--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: saleor_core
  labels:
    app: saleor
  kubernetes.io/change-cause: first-deploy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: sa-core
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: saleor_core
      labels: 
        app: sa-core
        ver: "1.0"
    containers:
      - name: saleor_core
        image: gowthi1404/saleor-core:dev-19122022
        ports:
          - containerPort: 8000 
            protocol: TCP


    